Updateded configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3269,7 +3269,7 @@ EOF
 fi
 done
 
-for ac_header in limits.h utmp.h utmpx.h sgtty.h lastlog.h rpc/key_prot.h
+for ac_header in limits.h utmp.h utmpx.h lastlog.h rpc/key_prot.h
 do
 ac_ac_Header=`echo "ac_cv_header_$ac_header" | $ac_tr_sh`
 echo "$as_me:3275: checking for $ac_header" >&5
@@ -5091,7 +5091,7 @@ EOF
 fi
 done
 
-for ac_func in getgroups getspnam getusershell getutent initgroups setgroups updwtmp updwtmpx
+for ac_func in getspnam getutent initgroups updwtmp updwtmpx
 do
 ac_ac_var=`echo "ac_cv_func_$ac_func" | $ac_tr_sh`
 echo "$as_me:5097: checking for $ac_func" >&5
@@ -5277,8 +5277,8 @@ echo "${ECHO_T}$utmpdir" >&6
         fi
 done
 
-echo "$as_me:5280: checking location of faillog/lastlog/wtmp" >&5
-echo $ECHO_N "checking location of faillog/lastlog/wtmp... $ECHO_C" >&6
+echo "$as_me:5280: checking location of lastlog/wtmp" >&5
+echo $ECHO_N "checking location of lastlog/wtmp... $ECHO_C" >&6
 for logdir in /var/log /var/adm /usr/adm /etc; do
         if test -d $logdir; then
                 cat >>confdefs.h <<EOF
@@ -5289,11 +5289,7 @@ EOF
 #define LASTLOG_FILE "$logdir/lastlog"
 EOF
 
-                cat >>confdefs.h <<EOF
-#define FAILLOG_FILE "$logdir/faillog"
-EOF
-
-                echo "$as_me:5296: result: $logdir" >&5
+                echo "$as_me:5292: result: $logdir" >&5
 echo "${ECHO_T}$logdir" >&6
                 break
         fi
@@ -5379,7 +5375,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:5382: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:5378: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -5554,7 +5550,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:5557: error: ambiguous option: $1
+    { { echo "$as_me:5553: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -5581,12 +5577,12 @@ Try \`$0 --help' for more information." >&2;}
   'config.h' ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:5584: error: unrecognized option: $1
+  -*) { { echo "$as_me:5580: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:5589: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:5585: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -5825,7 +5821,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:5828: creating $ac_file" >&5
+    { echo "$as_me:5824: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -5843,7 +5839,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5846: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5842: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5856,7 +5852,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5859: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5855: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5916,7 +5912,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:5919: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:5915: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -5927,7 +5923,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:5930: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:5926: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -5940,7 +5936,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:5943: error: cannot find input file: $f" >&5
+           { { echo "$as_me:5939: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -6057,7 +6053,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:6060: $ac_file is unchanged" >&5
+      { echo "$as_me:6056: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
